# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrasena', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('historial', '0001_initial'),
        ('proveedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORDEN_DE_COMPRA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('impreso', models.BooleanField(default=False)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('autorizada', models.BooleanField(default=False)),
                ('comentario', models.CharField(default='', max_length=300)),
                ('autorizo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='autorizo', to='usuarios.Perfil')),
                ('doc_contra', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contrasena_id', to='contrasena.CONTRASENA')),
                ('documento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relacion_orden', to='historial.HISTORIAL')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.DOCUMENTO_POR_TIENDA')),
                ('proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedor.PROVEEDOR')),
                ('solicita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='usuarios.Perfil')),
            ],
        ),
    ]
