# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedor', '0001_initial'),
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CONTRASENA',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('fehca_registro', models.DateField()),
                ('correlativo', models.IntegerField(default=1)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=300)),
            ],
        ),
        migrations.CreateModel(
            name='CONTRASENA_ACTUAL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.IntegerField(default=1)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_proveedor', to='proveedor.PROVEEDOR')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pass_store', to='tienda.EMPRESA')),
            ],
        ),
        migrations.AddField(
            model_name='contrasena',
            name='ubicado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contrasena.CONTRASENA_ACTUAL'),
        ),
    ]
