# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('cobro', '0001_initial'),
        ('tienda', '0001_initial'),
        ('producto', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CORRELATIVO_INFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField()),
                ('fecha_a_registrar', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='HISTORIAL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serie', models.CharField(default='', max_length=5)),
                ('documento', models.CharField(max_length=300)),
                ('fehca_registro', models.DateField()),
                ('fecha_documento', models.DateField(auto_now_add=True)),
                ('cliente_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.PERSONA')),
                ('ingresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('lista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.DOCUMENTO_POR_TIENDA')),
            ],
        ),
        migrations.CreateModel(
            name='INFILE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField()),
                ('huella', models.CharField(default='', max_length=300)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.CORRELATIVO_INFILE')),
            ],
        ),
        migrations.CreateModel(
            name='LISTA_PRODUCTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('cantidad', models.IntegerField(default=0)),
                ('unitario', models.DecimalField(decimal_places=4, default=0, max_digits=300)),
                ('entregado', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.DOCUMENTO_POR_TIENDA')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.PRODUCTO')),
            ],
        ),
        migrations.CreateModel(
            name='RECHAZO_IMPRESION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_eliminacion', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historial.HISTORIAL')),
            ],
        ),
        migrations.CreateModel(
            name='RECIBO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField(default=1)),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.EMPRESA')),
            ],
        ),
        migrations.AddField(
            model_name='correlativo_infile',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='historial.HISTORIAL'),
        ),
        migrations.AddField(
            model_name='correlativo_infile',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cobro.DOCUMENTOS_POR_CAJA'),
        ),
    ]
