# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180226_2057'),
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RECORD_DE_VENTAS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('record', models.DecimalField(decimal_places=4, default=0, max_digits=300)),
                ('facturas', models.ManyToManyField(related_name='documentos', to='historial.HISTORIAL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor', to='usuarios.Perfil')),
            ],
        ),
    ]
