# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 15:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
        ('historial', '0002_record_de_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='record_de_ventas',
            name='tienda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tienda_facturada', to='tienda.EMPRESA'),
            preserve_default=False,
        ),
    ]
