# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0001_initial'),
        ('tienda', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(default='', max_length=300)),
                ('credito', models.BooleanField(default=False)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('dias_credito', models.IntegerField(default=0)),
                ('mayorista', models.BooleanField(default=False)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.PERSONA')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.EMPRESA')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
            ],
        ),
    ]
