# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0006_usuario_tienda_proforma'),
    ]

    operations = [
        migrations.CreateModel(
            name='PROFORMA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atencion', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.CharField(blank=True, max_length=100)),
                ('fehca_registro', models.DateField()),
                ('fecha_vencimiento', models.DateField(auto_now_add=True)),
                ('lista', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.DOCUMENTO_POR_TIENDA')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
            ],
        ),
    ]
