# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DETALLE',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FICHA_TECNICA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LISTA_DETALLES',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dimension', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalle.DETALLE')),
            ],
        ),
        migrations.CreateModel(
            name='LISTADO_DET',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_DE_MEDIDA',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('acortado', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='lista_detalles',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalle.TIPO_DE_MEDIDA'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalle.LISTA_DETALLES'),
        ),
        migrations.AddField(
            model_name='ficha_tecnica',
            name='listado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detalle.LISTADO_DET'),
        ),
    ]
