# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-25 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_salario_mensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='PERMISOS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde_fecha', models.DateField()),
                ('hasta_fecha', models.DateField()),
                ('solicitud', models.CharField(default='vacaciones', max_length=300)),
                ('Perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='salario_mensual',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=300),
        ),
    ]
