# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20180225_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisos',
            old_name='desde_fecha',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='hasta_fecha',
        ),
    ]
