# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20180226_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='autorizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permisos',
            name='motivo',
            field=models.CharField(default='', max_length=300),
        ),
    ]
