# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='INVENTARIO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('distribuidor', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('mayorista', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.PRODUCTO')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.EMPRESA')),
            ],
        ),
    ]
