# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marca', '0001_initial'),
        ('detalle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODIGO',
            fields=[
                ('nombre', models.CharField(max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DESCRIPCION',
            fields=[
                ('detalle', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='IMAGENES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(default='', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.CODIGO')),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.DESCRIPCION')),
                ('detalles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detalle.LISTADO_DET')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO_IMAGEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.IMAGENES')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.PRODUCTO')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO_SET',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SET',
            fields=[
                ('numero', models.CharField(default='-', max_length=300, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='producto_set',
            name='id_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_set', to='producto.SET'),
        ),
        migrations.AddField(
            model_name='producto_set',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='producto.PRODUCTO'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.SET'),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marca.MARCA'),
        ),
    ]
